name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deployment:
    environment: VPS
    runs-on: ubuntu-latest
    steps:
      - name: clone on VPS and restart bot
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY}}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/eve/eggbot_source
            python3 -m venv .direnv
            git fetch origin main
            git reset --hard origin/main
            cat pid | xargs kill
            python3 eggbot.py &> log & echo $! > pid
            exit
