name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deployment:
    environment: VPS
    runs-on: ubuntu-latest
    steps:
      - name: clone on VPS and restart bot
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY}}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/eve/eggbot_source
            git fetch origin main
            git reset --hard origin/main
            source .direnv/python-3.10.12/bin/activate
            pip install -r requirements.txt --quiet
            sudo systemctl restart eggbot
            exit
